name: Run Flyway Migration

on:
  workflow_dispatch: # manual trigger via GitHub UI

jobs:
  run-migration:
    name: Trigger Flyway ECS Task
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Run ECS task
        run: |
          CLUSTER_NAME="SharedCluster"  # Update if needed
          TASK_DEF=$(aws ecs describe-task-definition --task-definition FlywayMigrationTask-FlywayTaskDef --query 'taskDefinition.taskDefinitionArn' --output text)
          SUBNET_IDS=$(aws ec2 describe-subnets --filters "Name=tag:Name,Values=private-subnet*" --query "Subnets[*].SubnetId" --output text)
          SECURITY_GROUP_ID=$(aws ec2 describe-security-groups --filters "Name=group-name,Values=FlywayTaskSG" --query "SecurityGroups[0].GroupId" --output text)

          echo "Running task: $TASK_DEF"

          aws ecs run-task \
            --cluster $CLUSTER_NAME \
            --launch-type FARGATE \
            --network-configuration "awsvpcConfiguration={subnets=[$SUBNET_IDS],securityGroups=[$SECURITY_GROUP_ID],assignPublicIp=ENABLED}" \
            --task-definition $TASK_DEF
