name: Publish Flyway Image to ECR

on:
  push:
    branches: [main]  # Only trigger on merge/push to main

jobs:
  build-and-push:
    name: Build and Push Flyway Image
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.set-tag.outputs.image-tag }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image tag
        id: set-tag
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          echo "image-tag=v$TIMESTAMP" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        run: |
          IMAGE_TAG=${{ steps.set-tag.outputs.image-tag }}
          IMAGE_URI=890742562318.dkr.ecr.us-east-1.amazonaws.com/flyway-migrations:$IMAGE_TAG

          echo "Building image with tag $IMAGE_TAG..."
          docker build -t $IMAGE_URI .

          echo "Pushing to ECR..."
          docker push $IMAGE_URI
